name: Typecheck

on:
  push:
    branches: [eugene/test-workflow]
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'poetry'
      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311
      - name: Get changed files
        uses: tj-actions/changed-files@v32
        id: changed_files
      - name: Show only new files
        run: echo "${{ steps.changed_files.outputs.added_files }}"

