name: Typecheck

on:
  push:
    branches: [eugene/test-workflow]
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'poetry'
      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311
      - name: Get new files added in the PR
        id: get_new_files
        run: |
            git fetch origin main
            git diff --name-only --diff-filter=A origin/main HEAD | grep '\.py$'
            NEW_FILES=$(git diff --name-only --diff-filter=A origin/main HEAD | grep '\.py$')
