name: Automated Migrations

on:
  push:
    branches: [ TLK-580_automated_migrations ]
jobs:
  run-alembic-migrations-ssh:
    runs-on: ubuntu-latest
    environment: production
    env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER_NAME: ${{secrets.SSH_USER_NAME}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        MIGRATION_API_ENDPOINT: ${{secrets.MIGRATION_API_ENDPOINT}}
        MIGRATION_API_TOKEN: ${{secrets.MIGRATION_API_TOKEN}}
        PROJECT_DIR: '~/cohere-toolkit'
        # Check if the migration API params are present we will use the migration API to run migrations.
        USE_MIGRATION_API: ${{ (secrets.MIGRATION_API_ENDPOINT != '') && (secrets.MIGRATION_API_TOKEN != '') }}
        # Check if the database URL is present we will use the database URL to run migrations.
        # Please note that the database connection should be open to the IP from where the migrations are being run.
        USE_DATABASE_URL: ${{ secrets.DATABASE_URL != '' }}
        # Check if the SSH params or all params are present we will use SSH to run migrations.
        USE_SSH: ${{ (secrets.SSH_PRIVATE_KEY != '') && (secrets.SSH_HOST != '') && (secrets.SSH_USER_NAME != '') }}

    steps:
        - name: Run Alembic Migrations SSH
          if: ${{ (env.USE_SSH == 'true' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'false') || (env.USE_SSH == 'true' && env.USE_MIGRATION_API == 'true' && env.USE_DATABASE_URL == 'true') }}
          run: |
            env
            echo "Running migrations using SSH"
            echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USER_NAME}@${SSH_HOST}
#              # Now we have got the access of EC2 and we will start the deploy .
              cd $PROJECT_DIR &&
              pwd   
              '
        - name: Run Alembic Migrations API
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'true' && env.USE_DATABASE_URL == 'false') }}
          run: |
            echo "Running migrations using the migration API"
        - name: Run Alembic Migrations Database
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'true') }}
          run: |
            echo "Running migrations using the database URL"
        - name: Fail Migration
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'false') }}
          run: |
            echo "Migaration failed. Please provide either SSH, Migration API or Database URL environment variables."
