name: Automated Migrations

on:
  push:
    branches: [ TLK-580_automated_migrations ]
jobs:
  run-alembic-migrations-ssh:
    runs-on: ubuntu-latest
    environment: production
    env:
        SSH_PROJECT_DIR: ${{ secrets.SSH_PROJECT_DIR }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER_NAME: ${{secrets.SSH_USER_NAME}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        MIGRATION_API_ENDPOINT: ${{secrets.MIGRATION_API_ENDPOINT}}
        MIGRATION_API_TOKEN: ${{secrets.MIGRATION_API_TOKEN}}
        # Check if the migration API params are present we will use the migration API to run migrations.
        USE_MIGRATION_API: ${{ (secrets.MIGRATION_API_ENDPOINT != '') && (secrets.MIGRATION_API_TOKEN != '') }}
        # Check if the database URL is present we will use the database URL to run migrations.
        # Please note that the database connection should be open to the IP from where the migrations are being run.
        USE_DATABASE_URL: ${{ secrets.DATABASE_URL != '' }}
        # Check if the SSH params or all params are present we will use SSH to run migrations.
        USE_SSH: ${{ (secrets.SSH_PRIVATE_KEY != '') && (secrets.SSH_HOST != '') && (secrets.SSH_USER_NAME != '') && (secrets.SSH_PROJECT_DIR != '')}}

    steps:
        - name: Run Alembic Migrations SSH
          if: ${{ (env.USE_SSH == 'true' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'false') }}
          run: |
            echo "Running migrations using SSH"
            echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USER_NAME}@${SSH_HOST} '
                export SSH_PROJECT_DIR=~/cohere-toolkit && # Set the project directory here
                sh $SSH_PROJECT_DIR/.github/scripts/run_docker_migration.sh && # Delete this command if your toolkit is not in a docker container
                sh $SSH_PROJECT_DIR/.github/scripts/run_src_migration.sh # Delete this command if your toolkit is in a docker container
            '
        - name: Run Alembic Migrations API
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'true' && env.USE_DATABASE_URL == 'false') }}
          run: |
            echo "Running migrations using the migration API"
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Run Alembic Migrations Database
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'true')  || (env.USE_SSH == 'true' && env.USE_MIGRATION_API == 'true' && env.USE_DATABASE_URL == 'true') }}
          run: |
            echo "Running migrations using the database URL"
            pip -V
            pip install poetry==1.7.1
            poetry install
            echo "DATABASE_URL=$DATABASE_URL" > .env
            alembic -c src/backend/alembic.ini upgrade head
        - name: Fail Migration
          if: ${{ (env.USE_SSH == 'false' && env.USE_MIGRATION_API == 'false' && env.USE_DATABASE_URL == 'false') }}
          run: |
            echo "Migaration failed. Please provide either SSH, Migration API or Database URL environment variables."
